'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@clerk/nextjs';
import Link from 'next/link';
import { Loader2, Printer, ArrowLeft, FileDown, ClipboardCopy, Check, Sparkles } from 'lucide-react';
import type { DomainRatings } from '@/types/onet';

// ── Types ─────────────────────────────────────────────────────────────────────

interface Element {
  elementId: string;
  elementName: string;
  rating: number;       // 0–3
  onetImportance: number;
}

interface DomainBlock {
  domain: string;
  label: string;
  elements: Element[];
  avg: number;
}

// ── Constants ─────────────────────────────────────────────────────────────────

const DOMAIN_LABELS: Record<string, string> = {
  skills: 'Skills',
  knowledge: 'Knowledge Areas',
  work_styles: 'Work Styles',
  abilities: 'Abilities',
  work_activities: 'Work Activities',
  work_context: 'Work Context',
  job_zone: 'Job Zone',
  interests: 'Interests',
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function today() {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}

function avg(elements: Element[]) {
  if (!elements.length) return 0;
  const rated = elements.filter((e) => e.rating > 0);
  if (!rated.length) return 0;
  return rated.reduce((s, e) => s + e.rating, 0) / rated.length;
}

// ── Bar component ─────────────────────────────────────────────────────────────

function MiniBar({ value, max = 3 }: { value: number; max?: number }) {
  const pct = (value / max) * 100;
  const color = value === 3 ? '#2A8B8B' : value === 2 ? '#0A4F4F' : value === 1 ? '#5b9fbf' : '#d1d5db';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flex: 1 }}>
      <div style={{ flex: 1, height: '6px', backgroundColor: '#E6F3F3', borderRadius: '99px', overflow: 'hidden' }}>
        <div style={{ width: `${pct}%`, height: '6px', backgroundColor: color, borderRadius: '99px' }} />
      </div>
      <span style={{ width: '16px', textAlign: 'right', fontSize: '11px', fontWeight: '700', color: value === 0 ? '#ccc' : '#0A4F4F', fontFamily: 'system-ui, sans-serif' }}>
        {value}
      </span>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ReportPage() {
  const router = useRouter();
  const { isSignedIn, isLoaded } = useUser();
  const [domains, setDomains] = useState<DomainBlock[]>([]);
  const [occupationTitle, setOccupationTitle] = useState('');
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [wantDoc, setWantDoc] = useState(false);

  function buildResumeText(title: string, blocks: DomainBlock[]) {
    const BAR = ['░░░', '█░░', '██░', '███'];
    const lines: string[] = [
      'SKILL-PRINT',
      `Target Role: ${title}`,
      'Generated by getmyskillprint.com · Based on O*NET / U.S. Dept. of Labor',
      '',
    ];
    for (const block of blocks) {
      const avgPct = Math.round((block.avg / 3) * 100);
      lines.push(`${block.label.toUpperCase()}  —  ${block.avg.toFixed(1)}/3  (${avgPct}%)`);
      for (const el of block.elements) {
        const bar = BAR[el.rating] ?? '░░░';
        lines.push(`  ${bar}  ${el.elementName}`);
      }
      lines.push('');
    }
    return lines.join('\n');
  }

  async function copyResumeSection() {
    const text = buildResumeText(occupationTitle, domains);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  useEffect(() => {
    // Fall back to localStorage backup in case Clerk auth redirect cleared sessionStorage
    const raw = sessionStorage.getItem('chq_results_payload')
      ?? localStorage.getItem('chq_results_payload_backup');
    if (!raw) { router.push('/assess'); return; }
    // Keep sessionStorage in sync
    sessionStorage.setItem('chq_results_payload', raw);

    const payload = JSON.parse(raw) as {
      occupationCode: string;
      occupationTitle: string;
      ratings: DomainRatings[];
    };

    setOccupationTitle(payload.occupationTitle);

    const blocks: DomainBlock[] = (payload.ratings ?? []).map((d) => ({
      domain: d.domain,
      label: DOMAIN_LABELS[d.domain] ?? d.domain,
      elements: d.elements ?? [],
      avg: avg(d.elements ?? []),
    }));

    setDomains(blocks);
    setLoading(false);
  }, [router]);

  if (!isLoaded || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-brand-600" />
      </div>
    );
  }

  // Require sign-in to view/save
  if (!isSignedIn) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-6">
        <div className="max-w-sm w-full text-center">
          <img src="/logo.svg" alt="Skill-Print" className="h-8 w-auto mx-auto mb-8" />
          <h1 className="text-2xl font-bold text-gray-900 mb-3">Sign in to view your report</h1>
          <p className="text-gray-500 mb-8">
            Create a free account to save your Skill-Print and revisit it any time.
          </p>
          <Link
            href="/sign-up?redirect=/report"
            className="block py-3.5 px-6 rounded-xl bg-brand-700 text-white font-bold hover:bg-brand-800 transition-colors mb-3"
          >
            Create free account →
          </Link>
          <Link
            href="/sign-in?redirect=/report"
            className="block py-3 px-6 rounded-xl border border-gray-200 text-gray-600 font-medium hover:bg-gray-50 transition-colors"
          >
            Sign in
          </Link>
        </div>
      </div>
    );
  }

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; background: white; }
          .report-card { box-shadow: none !important; border: none !important; border-radius: 0 !important; }
        }
        @page { size: letter portrait; margin: 0.6in 0.75in; }
      `}</style>

      {/* Back nav — minimal, no-print */}
      <div className="no-print bg-white border-b border-gray-100 px-6 py-3 flex items-center justify-between">
        {typeof window !== 'undefined' && sessionStorage.getItem('chq_results_payload') ? (
          <button onClick={() => router.back()} className="flex items-center gap-2 text-sm text-gray-500 hover:text-brand-700 transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to results
          </button>
        ) : (
          <Link href="/dashboard" className="flex items-center gap-2 text-sm text-gray-500 hover:text-brand-700 transition-colors">
            <ArrowLeft className="w-4 h-4" /> My dashboard
          </Link>
        )}
        <Link href="/" className="text-sm text-gray-400 hover:text-brand-700 transition-colors">
          <img src="/logo.svg" alt="Skill-Print" className="h-6 w-auto" />
        </Link>
      </div>

      {/* Report */}
      <div className="min-h-screen bg-gray-100 py-10 px-6">

        {/* Action buttons — directly above the card, hidden on print */}
        <div className="no-print max-w-[680px] mx-auto mb-3 flex items-center justify-end gap-3 flex-wrap">
          <button
            onClick={copyResumeSection}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-gray-200 bg-white text-gray-600 text-sm font-medium hover:bg-gray-50 transition-colors shadow-sm"
          >
            {copied
              ? <><Check className="w-4 h-4 text-emerald-500" /> Copied!</>
              : <><ClipboardCopy className="w-4 h-4" /> Copy section</>
            }
          </button>
          <a
            href="/templates/skill-print-resume-template.docx"
            download
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-gray-200 bg-white text-gray-600 text-sm font-medium hover:bg-gray-50 transition-colors shadow-sm"
          >
            <FileDown className="w-4 h-4" /> Word template
          </a>
          <a
            href="/templates/skill-print-resume-template.docx"
            download="skill-print-resume-template.docx"
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-gray-200 bg-white text-gray-600 text-sm font-medium hover:bg-gray-50 transition-colors shadow-sm"
            title="Download and upload to Google Drive → File → Open with Google Docs"
          >
            <FileDown className="w-4 h-4" /> Google Docs template
          </a>
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 px-5 py-2 rounded-xl bg-brand-700 text-white font-bold text-sm hover:bg-brand-800 transition-colors shadow-sm"
          >
            <Printer className="w-4 h-4" /> Save as PDF
          </button>
        </div>

        {/* Feedback nudge — want scores auto-filled into the Word doc? */}
        {!wantDoc && (
          <div className="no-print max-w-[680px] mx-auto mb-4 flex items-center gap-3 bg-white border border-brand-100 rounded-xl px-4 py-3 shadow-sm">
            <Sparkles className="w-4 h-4 text-accent-500 flex-shrink-0" />
            <p className="text-sm text-gray-600 flex-1">
              Want your scores auto-filled into the Word template?
            </p>
            <button
              onClick={() => setWantDoc(true)}
              className="text-xs font-bold text-brand-700 hover:text-brand-800 whitespace-nowrap transition-colors"
            >
              Yes, I want this →
            </button>
          </div>
        )}
        {wantDoc && (
          <div className="no-print max-w-[680px] mx-auto mb-4 flex items-center gap-3 bg-brand-50 border border-brand-200 rounded-xl px-4 py-3 shadow-sm">
            <Check className="w-4 h-4 text-brand-600 flex-shrink-0" />
            <p className="text-sm text-brand-700 font-medium">
              Got it — we'll add auto-filled Word &amp; Google Docs export soon. Thanks for the nudge!
            </p>
          </div>
        )}

        <div
          className="report-card max-w-[680px] mx-auto bg-white shadow-xl rounded-2xl overflow-hidden"
          style={{ fontFamily: 'system-ui, sans-serif' }}
        >
          {/* Header */}
          <div style={{ backgroundColor: '#0A4F4F', padding: '24px 40px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <div style={{ color: '#fff', fontSize: '17px', fontWeight: '800', letterSpacing: '0.06em' }}>CLAREERHQ</div>
                <div style={{ color: '#7BBFBF', fontSize: '10px', marginTop: '2px' }}>Your HQ for career clarity</div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ color: '#7BBFBF', fontSize: '9px', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Generated</div>
                <div style={{ color: '#fff', fontSize: '10px', marginTop: '2px' }}>{today()}</div>
              </div>
            </div>
          </div>

          <div style={{ padding: '32px 40px' }}>

            {/* Skill-Print label + role */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
              <span style={{ backgroundColor: '#0A4F4F', color: '#fff', fontSize: '9px', fontWeight: '800', letterSpacing: '0.12em', textTransform: 'uppercase', padding: '3px 10px', borderRadius: '99px' }}>
                Skill-Print
              </span>
              <div style={{ flex: 1, height: '1px', backgroundColor: '#E6F3F3' }} />
            </div>
            <h1 style={{ fontSize: '24px', fontWeight: '800', color: '#111', marginBottom: '2px' }}>
              {occupationTitle}
            </h1>
            <div style={{ color: '#999', fontSize: '11px', marginBottom: '28px' }}>
              Based on U.S. Department of Labor occupational data
            </div>

            {/* Domain blocks */}
            {domains.map((block, bi) => {
              const avgVal = block.avg;
              const avgPct = Math.round((avgVal / 3) * 100);
              return (
                <div key={block.domain} style={{ marginBottom: bi < domains.length - 1 ? '28px' : '0' }}>
                  {/* Domain header row */}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px', paddingBottom: '6px', borderBottom: '1.5px solid #E6F3F3' }}>
                    <span style={{ fontSize: '11px', fontWeight: '800', color: '#0A4F4F', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                      {block.label}
                    </span>
                    <span style={{ fontSize: '11px', fontWeight: '700', color: '#2A8B8B' }}>
                      Avg {avgVal.toFixed(1)}/3 &nbsp;·&nbsp; {avgPct}%
                    </span>
                  </div>

                  {/* Element rows */}
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4px 24px' }}>
                    {block.elements.map((el) => (
                      <div key={el.elementId} style={{ display: 'flex', alignItems: 'center', gap: '8px', paddingBottom: '3px' }}>
                        <span style={{ fontSize: '10.5px', color: el.rating === 0 ? '#bbb' : '#444', minWidth: '130px', flex: 1 }}>
                          {el.elementName}
                        </span>
                        <MiniBar value={el.rating} />
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}

            {/* Resume callout */}
            <div style={{ marginTop: '28px', border: '1.5px dashed #2A8B8B', borderRadius: '10px', padding: '14px 18px', backgroundColor: '#f7fefe' }}>
              <div style={{ fontSize: '10px', fontWeight: '800', color: '#0A4F4F', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '5px' }}>
                Using this on your resume
              </div>
              <div style={{ fontSize: '11.5px', color: '#555', lineHeight: 1.6 }}>
                Add a <strong>Skill-Print</strong> section directly below your Summary — before Experience.
                Include your target role and domain scores. Download the free resume template above to get started instantly.
              </div>
            </div>

            {/* Footer */}
            <div style={{ marginTop: '24px', paddingTop: '14px', borderTop: '1px solid #E6F3F3', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ fontSize: '9px', color: '#bbb' }}>Occupational data: U.S. Department of Labor</span>
              <span style={{ fontSize: '9px', color: '#2A8B8B', fontWeight: '700' }}>getmyskillprint.com</span>
            </div>

          </div>
        </div>

        {/* Google Docs note */}
        <div className="no-print max-w-[680px] mx-auto mt-4 text-center">
          <p className="text-xs text-gray-400">
            <strong>Google Docs:</strong> download the template, then upload to drive.google.com → open with Google Docs.
          </p>
        </div>
      </div>
    </>
  );
}
